apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl: 
    manifests:
      - "k8s/dev/client.yml"
      - "k8s/dev/nest.yml"
      - "k8s/dev/config.yml"
      - "k8s/dev/ingress.yml"
      - "k8s/dev/db.yml"
      - "k8s/dev/auth.yml"
build:
  artifacts:
    # - image: nginx-dev
    #   context: nginx
    #   platforms: [linux/amd64, linux/arm64]
    #   docker: 
    #     dockerfile: Dockerfile
    #   sync: 
    #     manual: 
    #       - src: 'default.conf'
    #         dest: .
    - image: api-dev
      context: api
      platforms: [linux/amd64, linux/arm64]
      docker: 
        dockerfile: Dockerfile.dev
      sync: 
        manual: 
          - src: '**/*.ts'
            dest: .
          - src: '**/*.js'
            dest: .
    - image: client-dev
      context: client
      platforms: [linux/amd64, linux/arm64]
      docker: 
        dockerfile: Dockerfile.dev
      sync: 
        manual: 
          - src: '**/*.ts'
            dest: .
          - src: '**/*.js'
            dest: .
          - src: '**/*.tsx'
            dest: .
          - src: '**/*.jsx'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .