apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: chelsea
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'chelsea.brown1@ca.ey.com'
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
